name: kieflings
favicon: null
layout_spectrum: 0
typography_spectrum: 0.45245753904374675
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebede8'
    - '#000000'
    - '#8b918d'
    - '#6a1217'
    - '#784021'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
