name: kieflings
favicon: null
layout_spectrum: 0
typography_spectrum: 0.45245753904374675
title: The kieflings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.666666
  lightness: 0.953828
  saturation: 0.512387
  rhythmicContrast: 0.644722
purpose:
  - name: null
    item: null
    url: null
